driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.6
  - name: centos-7.1
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[tar::default]
      - recipe[tar_test::default]
