addons:
  apt:
    sources:
      - chef-current-xenial
    packages:
      - chef-workstation

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

env:
  - CHEF_LICENSE=accept

branches:
  only:
    - master

services: docker

env:
  global:
  - CHEF_LICENSE="accept-no-persist"
  matrix:
  - INSTANCE=resources-centos-6
  - INSTANCE=resources-centos-7
  - INSTANCE=resources-debian-8
  - INSTANCE=resources-debian-9
  - INSTANCE=resources-fedora-latest
  - INSTANCE=resources-opensuse-leap
  - INSTANCE=resources-ubuntu-1604

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version

script: KITCHEN_LOCAL_YAML=kitchen.dokken.yml kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - chef exec delivery local all
      env:
        - UNIT_AND_LINT=1
        - CHEF_LICENSE=accept
